"""
AURA Nutrition Database
Stores per-100g nutritional data for common fruits.
"""


class NutritionDB:
    """In-memory fruit nutrition database (per 100 g serving)."""

    DATA = {
        "Apple": {
            "calories": 52,
            "protein": 0.3,
            "carbs": 13.8,
            "fat": 0.2,
            "fiber": 2.4,
            "sugar": 10.4,
            "water": 85.6,
            "vitamins": {
                "Vitamin C": 4.6,
                "Vitamin A": 0.054,
                "Vitamin K": 2.2,
                "Vitamin B6": 0.041,
            },
            "minerals": {
                "Potassium": 107,
                "Calcium": 6,
                "Magnesium": 5,
                "Phosphorus": 11,
                "Iron": 0.12,
            },
        },
        "Banana": {
            "calories": 89,
            "protein": 1.1,
            "carbs": 22.8,
            "fat": 0.3,
            "fiber": 2.6,
            "sugar": 12.2,
            "water": 74.9,
            "vitamins": {
                "Vitamin C": 8.7,
                "Vitamin A": 0.064,
                "Vitamin B6": 0.367,
                "Vitamin K": 0.5,
            },
            "minerals": {
                "Potassium": 358,
                "Calcium": 5,
                "Magnesium": 27,
                "Phosphorus": 22,
                "Iron": 0.26,
            },
        },
        "Orange": {
            "calories": 47,
            "protein": 0.9,
            "carbs": 11.8,
            "fat": 0.1,
            "fiber": 2.4,
            "sugar": 9.4,
            "water": 86.8,
            "vitamins": {
                "Vitamin C": 53.2,
                "Vitamin A": 0.225,
                "Vitamin B6": 0.06,
                "Vitamin K": 0.0,
            },
            "minerals": {
                "Potassium": 181,
                "Calcium": 40,
                "Magnesium": 10,
                "Phosphorus": 14,
                "Iron": 0.1,
            },
        },
        "Strawberry": {
            "calories": 32,
            "protein": 0.7,
            "carbs": 7.7,
            "fat": 0.3,
            "fiber": 2.0,
            "sugar": 4.9,
            "water": 91.0,
            "vitamins": {
                "Vitamin C": 58.8,
                "Vitamin A": 0.012,
                "Vitamin B6": 0.047,
                "Vitamin K": 2.2,
            },
            "minerals": {
                "Potassium": 153,
                "Calcium": 16,
                "Magnesium": 13,
                "Phosphorus": 24,
                "Iron": 0.41,
            },
        },
        "Mango": {
            "calories": 60,
            "protein": 0.8,
            "carbs": 15.0,
            "fat": 0.4,
            "fiber": 1.6,
            "sugar": 13.7,
            "water": 83.5,
            "vitamins": {
                "Vitamin C": 36.4,
                "Vitamin A": 1.082,
                "Vitamin B6": 0.119,
                "Vitamin K": 4.2,
            },
            "minerals": {
                "Potassium": 168,
                "Calcium": 11,
                "Magnesium": 10,
                "Phosphorus": 14,
                "Iron": 0.16,
            },
        },
        "Pineapple": {
            "calories": 50,
            "protein": 0.5,
            "carbs": 13.1,
            "fat": 0.1,
            "fiber": 1.4,
            "sugar": 9.9,
            "water": 86.0,
            "vitamins": {
                "Vitamin C": 47.8,
                "Vitamin A": 0.058,
                "Vitamin B6": 0.112,
                "Vitamin K": 0.7,
            },
            "minerals": {
                "Potassium": 109,
                "Calcium": 13,
                "Magnesium": 12,
                "Phosphorus": 8,
                "Iron": 0.29,
            },
        },
        "Grape": {
            "calories": 69,
            "protein": 0.7,
            "carbs": 18.1,
            "fat": 0.2,
            "fiber": 0.9,
            "sugar": 15.5,
            "water": 80.5,
            "vitamins": {
                "Vitamin C": 3.2,
                "Vitamin A": 0.066,
                "Vitamin B6": 0.086,
                "Vitamin K": 14.6,
            },
            "minerals": {
                "Potassium": 191,
                "Calcium": 10,
                "Magnesium": 7,
                "Phosphorus": 20,
                "Iron": 0.36,
            },
        },
        "Watermelon": {
            "calories": 30,
            "protein": 0.6,
            "carbs": 7.6,
            "fat": 0.2,
            "fiber": 0.4,
            "sugar": 6.2,
            "water": 91.4,
            "vitamins": {
                "Vitamin C": 8.1,
                "Vitamin A": 0.569,
                "Vitamin B6": 0.045,
                "Vitamin K": 0.1,
            },
            "minerals": {
                "Potassium": 112,
                "Calcium": 7,
                "Magnesium": 10,
                "Phosphorus": 11,
                "Iron": 0.24,
            },
        },
        "Lemon": {
            "calories": 29,
            "protein": 1.1,
            "carbs": 9.3,
            "fat": 0.3,
            "fiber": 2.8,
            "sugar": 2.5,
            "water": 88.9,
            "vitamins": {
                "Vitamin C": 53.0,
                "Vitamin A": 0.022,
                "Vitamin B6": 0.08,
                "Vitamin K": 0.0,
            },
            "minerals": {
                "Potassium": 138,
                "Calcium": 26,
                "Magnesium": 8,
                "Phosphorus": 16,
                "Iron": 0.6,
            },
        },
        "Pomegranate": {
            "calories": 83,
            "protein": 1.7,
            "carbs": 18.7,
            "fat": 1.2,
            "fiber": 4.0,
            "sugar": 13.7,
            "water": 77.9,
            "vitamins": {
                "Vitamin C": 10.2,
                "Vitamin A": 0.0,
                "Vitamin B6": 0.075,
                "Vitamin K": 16.4,
            },
            "minerals": {
                "Potassium": 236,
                "Calcium": 10,
                "Magnesium": 12,
                "Phosphorus": 36,
                "Iron": 0.3,
            },
        },
        "Coconut": {
            "calories": 354,
            "protein": 3.3,
            "carbs": 15.2,
            "fat": 33.5,
            "fiber": 9.0,
            "sugar": 6.2,
            "water": 47.0,
            "vitamins": {
                "Vitamin C": 3.3,
                "Vitamin A": 0.0,
                "Vitamin B6": 0.054,
                "Vitamin K": 0.2,
            },
            "minerals": {
                "Potassium": 356,
                "Calcium": 14,
                "Magnesium": 32,
                "Phosphorus": 113,
                "Iron": 2.43,
            },
        },
        "Peach": {
            "calories": 39,
            "protein": 0.9,
            "carbs": 9.5,
            "fat": 0.3,
            "fiber": 1.5,
            "sugar": 8.4,
            "water": 88.9,
            "vitamins": {
                "Vitamin C": 6.6,
                "Vitamin A": 0.326,
                "Vitamin B6": 0.025,
                "Vitamin K": 2.6,
            },
            "minerals": {
                "Potassium": 190,
                "Calcium": 6,
                "Magnesium": 9,
                "Phosphorus": 20,
                "Iron": 0.25,
            },
        },
        "Jackfruit": {
            "calories": 95,
            "protein": 1.7,
            "carbs": 23.3,
            "fat": 0.6,
            "fiber": 1.5,
            "sugar": 19.1,
            "water": 73.5,
            "vitamins": {
                "Vitamin C": 13.7,
                "Vitamin A": 0.11,
                "Vitamin B6": 0.329,
                "Vitamin K": 0.0,
            },
            "minerals": {
                "Potassium": 448,
                "Calcium": 24,
                "Magnesium": 29,
                "Phosphorus": 21,
                "Iron": 0.23,
            },
        },
        "Custard Apple": {
            "calories": 94,
            "protein": 2.1,
            "carbs": 23.6,
            "fat": 0.3,
            "fiber": 4.4,
            "sugar": 18.2,
            "water": 73.2,
            "vitamins": {
                "Vitamin C": 36.3,
                "Vitamin A": 0.033,
                "Vitamin B6": 0.221,
                "Vitamin K": 0.0,
            },
            "minerals": {
                "Potassium": 382,
                "Calcium": 30,
                "Magnesium": 18,
                "Phosphorus": 21,
                "Iron": 0.71,
            },
        },
        "Fig": {
            "calories": 74,
            "protein": 0.8,
            "carbs": 19.2,
            "fat": 0.3,
            "fiber": 2.9,
            "sugar": 16.3,
            "water": 79.1,
            "vitamins": {
                "Vitamin C": 2.0,
                "Vitamin A": 0.142,
                "Vitamin B6": 0.113,
                "Vitamin K": 4.7,
            },
            "minerals": {
                "Potassium": 232,
                "Calcium": 35,
                "Magnesium": 17,
                "Phosphorus": 14,
                "Iron": 0.37,
            },
        },
    }

    def get_nutrition(self, fruit_name: str) -> dict | None:
        """Look up nutrition for a fruit (case-insensitive)."""
        for key, value in self.DATA.items():
            if key.lower() == fruit_name.lower():
                return {"name": key, "per_100g": value}
        # Return None if not found
        return None

    def list_fruits(self) -> list[str]:
        """Return all fruit names in the database."""
        return sorted(self.DATA.keys())
